[Settings]
CreateFileDeviceWhenNoDevs=true
;HighDPI=false
;LogFrameStats=false
;LogToStdout=false
;LogStackTrace=true
;LogRotateCount=10
;LogLeaveOldLogs=true
;SaveSettings=true
UseAppDataDir=true
;PixetIniInAppDataDir=false
;AppDataDir=
;PixetIni=
;ConfigsDir=
;LogsDir=
;FactoryDir=
;MaxFrameMemory=1024
;MainUi=devcontrol

[Hwlibs]
Hwlib=hwlibs/minipix.dll
Hwlib=hwlibs/widepix.dll
Hwlib=hwlibs/zem.dll
Hwlib=hwlibs/zest.dll
Hwlib=hwlibs/dummy.dll